export type ResourceType = 'VIDEO' | 'PDF' | 'LINK' | 'DOCUMENT';

export interface Resource {
  id: number;
  title: string;
  resource_type: ResourceType;
  node: number;
  google_drive_id?: string;
  external_url?: string;
  preview_link?: string; // Generated by your SerializerMethodField
  created_at: string;
  order: number;
}

export interface CreateResourcePayload {
  title: string;
  resource_type: ResourceType;
  node: number;
  // Use these to match your backend's "Smart Inputs"
  google_drive_link?: string; 
  external_url?: string;
}
